services:
  frontend:
    image: uniquecolor/miniproject-frontend:1.0.2
    container_name: frontend
    ports:
      - 80:80
    environment:
      - VITE_API_BASE_URL=http://192.168.0.1:8080

  gateway-service:
    image: uniquecolor/gateway-service:1.0.0
    build: ./gateway
    container_name: gateway-service
    ports:
      - "8080:8080"
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-service:8761/eureka/
      - CORS_ALLOWED_ORIGIN=http://192.168.0.1

  eureka-service:
    image: uniquecolor/eureka-service:1.0.0
    build: ./eureka-server
    container_name: eureka-service
    ports:
      - "8761:8761"

  config-service:
    image: uniquecolor/config-service:1.0.0
    build: ./config-server
    container_name: config-service

  account-service:
    image: uniquecolor/account-service:1.0.1
    build: ./account-service
    container_name: account-service
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-service:8761/eureka/
      - spring.datasource.url=jdbc:mariadb://mariadb-account-service:3306/appdb

  transaction-service:
    image: uniquecolor/transaction-service:1.0.1
    build: ./transaction-service
    container_name: transaction-service
    depends_on:
      kafka:
        condition: service_healthy
      schema-registry:
        condition: service_healthy
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-service:8761/eureka/
      - spring.kafka.bootstrap-servers=kafka:9092
      - spring.kafka.properties.schema.registry.url=http://schema-registry:8081
      - spring.datasource.url=jdbc:mariadb://mariadb-transaction-service:3306/appdb

  notification-service:
    image: uniquecolor/notification-service:1.0.1
    build: ./notification-service
    container_name: notification-service
    depends_on:
      kafka:
        condition: service_healthy
      schema-registry:
        condition: service_healthy
    ports:
      - "8085:8085"
    environment:
      spring.datasource.url: jdbc:mariadb://mariadb-notification-service:3306/appdb
      spring.h2.console.settings.web-allow-others: "true" # 임시조치
      eureka.client.service-url.defaultZone: http://eureka-service:8761/eureka/
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SCHEMA_REGISTRY_URL: http://schema-registry:8081

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: kafka
    hostname: kafka
    ports:
      - "29092:29092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092,CONTROLLER://kafka:9093,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      CLUSTER_ID: "mOS8beCYQmOoDVwrzVVf9A"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    volumes:
      - kafka-data:/var/lib/kafka/data
    healthcheck:
      test: ["CMD", "kafka-broker-api-versions", "--bootstrap-server", "kafka:9092"]
      interval: 10s
      timeout: 10s
      retries: 10

  schema-registry:
    image: confluentinc/cp-schema-registry:7.6.1
    container_name: schema-registry
    hostname: schema-registry
    depends_on:
      kafka:
        condition: service_healthy
    ports:
      - "8091:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:9092
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
      SCHEMA_REGISTRY_KAFKASTORE_TOPIC: _schemas
      SCHEMA_REGISTRY_SCHEMA_COMPATIBILITY_LEVEL: BACKWARD
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/subjects"]
      interval: 10s
      timeout: 10s
      retries: 10

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    depends_on:
      - kafka
      - schema-registry
    ports:
      - "8090:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: fin-account-hub
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_SCHEMAREGISTRY: http://schema-registry:8081

  mariadb-account-service:
    image: mariadb:latest
    container_name: mariadb-account-service
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: rootpassword
      MARIADB_DATABASE: appdb
      MARIADB_USER: appuser
      MARIADB_PASSWORD: apppassword
      
  mariadb-transaction-service:
    image: mariadb:latest
    container_name: mariadb-transaction-service
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: rootpassword
      MARIADB_DATABASE: appdb
      MARIADB_USER: appuser
      MARIADB_PASSWORD: apppassword
      
  mariadb-notification-service:
    image: mariadb:latest
    container_name: mariadb-notification-service
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: rootpassword
      MARIADB_DATABASE: appdb
      MARIADB_USER: appuser
      MARIADB_PASSWORD: apppassword

volumes:
  kafka-data:
