/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.finaccount.transactionservice;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

/** 계좌 입출금/이체 거래 발생 시 발행되는 이벤트. BACKWARD 호환성 유지를 위해 신규 필드는 반드시 default 값을 가져야 함. v2: 요구사항 정리 문서(fromAccount/toAccount FK 분리, status) 반영 — fromAccountId/toAccountId/status 추가. */
@org.apache.avro.specific.AvroGenerated
public class TransactionEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -5573437961724569020L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"TransactionEvent\",\"namespace\":\"com.finaccount.transactionservice\",\"doc\":\"계좌 입출금/이체 거래 발생 시 발행되는 이벤트. BACKWARD 호환성 유지를 위해 신규 필드는 반드시 default 값을 가져야 함. v2: 요구사항 정리 문서(fromAccount/toAccount FK 분리, status) 반영 — fromAccountId/toAccountId/status 추가.\",\"fields\":[{\"name\":\"transactionId\",\"type\":\"int\",\"doc\":\"거래 고유 ID\"},{\"name\":\"ownerName\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"거래 요청 사용자 이름\"},{\"name\":\"transactionType\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"DEPOSIT | WITHDRAW | TRANSFER (요구사항 정리 문서 기준)\"},{\"name\":\"amount\",\"type\":\"long\",\"doc\":\"거래 금액 (원 단위)\"},{\"name\":\"createdAt\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"거래 발생 시각 (ISO-8601)\"},{\"name\":\"fromAccountId\",\"type\":[\"null\",\"int\"],\"doc\":\"출금/이체 출발 계좌 ID (DEPOSIT은 null). 요구사항 정리(2) API 응답의 fromAccountId 대응\",\"default\":null},{\"name\":\"toAccountId\",\"type\":[\"null\",\"int\"],\"doc\":\"입금/이체 도착 계좌 ID (WITHDRAW는 null). 요구사항 정리(2) API 응답의 toAccountId 대응\",\"default\":null},{\"name\":\"status\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"PENDING | SUCCESS | FAILED (Saga 보상 트랜잭션 대응, 요구사항 정리 문서 Transaction DB status)\",\"default\":\"SUCCESS\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<TransactionEvent> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<TransactionEvent> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<TransactionEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<TransactionEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<TransactionEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this TransactionEvent to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a TransactionEvent from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a TransactionEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static TransactionEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** 거래 고유 ID */
  private int transactionId;
  /** 거래 요청 사용자 이름 */
  private java.lang.String ownerName;
  /** DEPOSIT | WITHDRAW | TRANSFER (요구사항 정리 문서 기준) */
  private java.lang.String transactionType;
  /** 거래 금액 (원 단위) */
  private long amount;
  /** 거래 발생 시각 (ISO-8601) */
  private java.lang.String createdAt;
  /** 출금/이체 출발 계좌 ID (DEPOSIT은 null). 요구사항 정리(2) API 응답의 fromAccountId 대응 */
  private java.lang.Integer fromAccountId;
  /** 입금/이체 도착 계좌 ID (WITHDRAW는 null). 요구사항 정리(2) API 응답의 toAccountId 대응 */
  private java.lang.Integer toAccountId;
  /** PENDING | SUCCESS | FAILED (Saga 보상 트랜잭션 대응, 요구사항 정리 문서 Transaction DB status) */
  private java.lang.String status;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public TransactionEvent() {}

  /**
   * All-args constructor.
   * @param transactionId 거래 고유 ID
   * @param ownerName 거래 요청 사용자 이름
   * @param transactionType DEPOSIT | WITHDRAW | TRANSFER (요구사항 정리 문서 기준)
   * @param amount 거래 금액 (원 단위)
   * @param createdAt 거래 발생 시각 (ISO-8601)
   * @param fromAccountId 출금/이체 출발 계좌 ID (DEPOSIT은 null). 요구사항 정리(2) API 응답의 fromAccountId 대응
   * @param toAccountId 입금/이체 도착 계좌 ID (WITHDRAW는 null). 요구사항 정리(2) API 응답의 toAccountId 대응
   * @param status PENDING | SUCCESS | FAILED (Saga 보상 트랜잭션 대응, 요구사항 정리 문서 Transaction DB status)
   */
  public TransactionEvent(java.lang.Integer transactionId, java.lang.String ownerName, java.lang.String transactionType, java.lang.Long amount, java.lang.String createdAt, java.lang.Integer fromAccountId, java.lang.Integer toAccountId, java.lang.String status) {
    this.transactionId = transactionId;
    this.ownerName = ownerName;
    this.transactionType = transactionType;
    this.amount = amount;
    this.createdAt = createdAt;
    this.fromAccountId = fromAccountId;
    this.toAccountId = toAccountId;
    this.status = status;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return transactionId;
    case 1: return ownerName;
    case 2: return transactionType;
    case 3: return amount;
    case 4: return createdAt;
    case 5: return fromAccountId;
    case 6: return toAccountId;
    case 7: return status;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: transactionId = (java.lang.Integer)value$; break;
    case 1: ownerName = value$ != null ? value$.toString() : null; break;
    case 2: transactionType = value$ != null ? value$.toString() : null; break;
    case 3: amount = (java.lang.Long)value$; break;
    case 4: createdAt = value$ != null ? value$.toString() : null; break;
    case 5: fromAccountId = (java.lang.Integer)value$; break;
    case 6: toAccountId = (java.lang.Integer)value$; break;
    case 7: status = value$ != null ? value$.toString() : null; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'transactionId' field.
   * @return 거래 고유 ID
   */
  public int getTransactionId() {
    return transactionId;
  }


  /**
   * Sets the value of the 'transactionId' field.
   * 거래 고유 ID
   * @param value the value to set.
   */
  public void setTransactionId(int value) {
    this.transactionId = value;
  }

  /**
   * Gets the value of the 'ownerName' field.
   * @return 거래 요청 사용자 이름
   */
  public java.lang.String getOwnerName() {
    return ownerName;
  }


  /**
   * Sets the value of the 'ownerName' field.
   * 거래 요청 사용자 이름
   * @param value the value to set.
   */
  public void setOwnerName(java.lang.String value) {
    this.ownerName = value;
  }

  /**
   * Gets the value of the 'transactionType' field.
   * @return DEPOSIT | WITHDRAW | TRANSFER (요구사항 정리 문서 기준)
   */
  public java.lang.String getTransactionType() {
    return transactionType;
  }


  /**
   * Sets the value of the 'transactionType' field.
   * DEPOSIT | WITHDRAW | TRANSFER (요구사항 정리 문서 기준)
   * @param value the value to set.
   */
  public void setTransactionType(java.lang.String value) {
    this.transactionType = value;
  }

  /**
   * Gets the value of the 'amount' field.
   * @return 거래 금액 (원 단위)
   */
  public long getAmount() {
    return amount;
  }


  /**
   * Sets the value of the 'amount' field.
   * 거래 금액 (원 단위)
   * @param value the value to set.
   */
  public void setAmount(long value) {
    this.amount = value;
  }

  /**
   * Gets the value of the 'createdAt' field.
   * @return 거래 발생 시각 (ISO-8601)
   */
  public java.lang.String getCreatedAt() {
    return createdAt;
  }


  /**
   * Sets the value of the 'createdAt' field.
   * 거래 발생 시각 (ISO-8601)
   * @param value the value to set.
   */
  public void setCreatedAt(java.lang.String value) {
    this.createdAt = value;
  }

  /**
   * Gets the value of the 'fromAccountId' field.
   * @return 출금/이체 출발 계좌 ID (DEPOSIT은 null). 요구사항 정리(2) API 응답의 fromAccountId 대응
   */
  public java.lang.Integer getFromAccountId() {
    return fromAccountId;
  }


  /**
   * Sets the value of the 'fromAccountId' field.
   * 출금/이체 출발 계좌 ID (DEPOSIT은 null). 요구사항 정리(2) API 응답의 fromAccountId 대응
   * @param value the value to set.
   */
  public void setFromAccountId(java.lang.Integer value) {
    this.fromAccountId = value;
  }

  /**
   * Gets the value of the 'toAccountId' field.
   * @return 입금/이체 도착 계좌 ID (WITHDRAW는 null). 요구사항 정리(2) API 응답의 toAccountId 대응
   */
  public java.lang.Integer getToAccountId() {
    return toAccountId;
  }


  /**
   * Sets the value of the 'toAccountId' field.
   * 입금/이체 도착 계좌 ID (WITHDRAW는 null). 요구사항 정리(2) API 응답의 toAccountId 대응
   * @param value the value to set.
   */
  public void setToAccountId(java.lang.Integer value) {
    this.toAccountId = value;
  }

  /**
   * Gets the value of the 'status' field.
   * @return PENDING | SUCCESS | FAILED (Saga 보상 트랜잭션 대응, 요구사항 정리 문서 Transaction DB status)
   */
  public java.lang.String getStatus() {
    return status;
  }


  /**
   * Sets the value of the 'status' field.
   * PENDING | SUCCESS | FAILED (Saga 보상 트랜잭션 대응, 요구사항 정리 문서 Transaction DB status)
   * @param value the value to set.
   */
  public void setStatus(java.lang.String value) {
    this.status = value;
  }

  /**
   * Creates a new TransactionEvent RecordBuilder.
   * @return A new TransactionEvent RecordBuilder
   */
  public static com.finaccount.transactionservice.TransactionEvent.Builder newBuilder() {
    return new com.finaccount.transactionservice.TransactionEvent.Builder();
  }

  /**
   * Creates a new TransactionEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new TransactionEvent RecordBuilder
   */
  public static com.finaccount.transactionservice.TransactionEvent.Builder newBuilder(com.finaccount.transactionservice.TransactionEvent.Builder other) {
    if (other == null) {
      return new com.finaccount.transactionservice.TransactionEvent.Builder();
    } else {
      return new com.finaccount.transactionservice.TransactionEvent.Builder(other);
    }
  }

  /**
   * Creates a new TransactionEvent RecordBuilder by copying an existing TransactionEvent instance.
   * @param other The existing instance to copy.
   * @return A new TransactionEvent RecordBuilder
   */
  public static com.finaccount.transactionservice.TransactionEvent.Builder newBuilder(com.finaccount.transactionservice.TransactionEvent other) {
    if (other == null) {
      return new com.finaccount.transactionservice.TransactionEvent.Builder();
    } else {
      return new com.finaccount.transactionservice.TransactionEvent.Builder(other);
    }
  }

  /**
   * RecordBuilder for TransactionEvent instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<TransactionEvent>
    implements org.apache.avro.data.RecordBuilder<TransactionEvent> {

    /** 거래 고유 ID */
    private int transactionId;
    /** 거래 요청 사용자 이름 */
    private java.lang.String ownerName;
    /** DEPOSIT | WITHDRAW | TRANSFER (요구사항 정리 문서 기준) */
    private java.lang.String transactionType;
    /** 거래 금액 (원 단위) */
    private long amount;
    /** 거래 발생 시각 (ISO-8601) */
    private java.lang.String createdAt;
    /** 출금/이체 출발 계좌 ID (DEPOSIT은 null). 요구사항 정리(2) API 응답의 fromAccountId 대응 */
    private java.lang.Integer fromAccountId;
    /** 입금/이체 도착 계좌 ID (WITHDRAW는 null). 요구사항 정리(2) API 응답의 toAccountId 대응 */
    private java.lang.Integer toAccountId;
    /** PENDING | SUCCESS | FAILED (Saga 보상 트랜잭션 대응, 요구사항 정리 문서 Transaction DB status) */
    private java.lang.String status;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.finaccount.transactionservice.TransactionEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.transactionId)) {
        this.transactionId = data().deepCopy(fields()[0].schema(), other.transactionId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.ownerName)) {
        this.ownerName = data().deepCopy(fields()[1].schema(), other.ownerName);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.transactionType)) {
        this.transactionType = data().deepCopy(fields()[2].schema(), other.transactionType);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.amount)) {
        this.amount = data().deepCopy(fields()[3].schema(), other.amount);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.createdAt)) {
        this.createdAt = data().deepCopy(fields()[4].schema(), other.createdAt);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.fromAccountId)) {
        this.fromAccountId = data().deepCopy(fields()[5].schema(), other.fromAccountId);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.toAccountId)) {
        this.toAccountId = data().deepCopy(fields()[6].schema(), other.toAccountId);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.status)) {
        this.status = data().deepCopy(fields()[7].schema(), other.status);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
    }

    /**
     * Creates a Builder by copying an existing TransactionEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(com.finaccount.transactionservice.TransactionEvent other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.transactionId)) {
        this.transactionId = data().deepCopy(fields()[0].schema(), other.transactionId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.ownerName)) {
        this.ownerName = data().deepCopy(fields()[1].schema(), other.ownerName);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.transactionType)) {
        this.transactionType = data().deepCopy(fields()[2].schema(), other.transactionType);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.amount)) {
        this.amount = data().deepCopy(fields()[3].schema(), other.amount);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.createdAt)) {
        this.createdAt = data().deepCopy(fields()[4].schema(), other.createdAt);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.fromAccountId)) {
        this.fromAccountId = data().deepCopy(fields()[5].schema(), other.fromAccountId);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.toAccountId)) {
        this.toAccountId = data().deepCopy(fields()[6].schema(), other.toAccountId);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.status)) {
        this.status = data().deepCopy(fields()[7].schema(), other.status);
        fieldSetFlags()[7] = true;
      }
    }

    /**
      * Gets the value of the 'transactionId' field.
      * 거래 고유 ID
      * @return The value.
      */
    public int getTransactionId() {
      return transactionId;
    }


    /**
      * Sets the value of the 'transactionId' field.
      * 거래 고유 ID
      * @param value The value of 'transactionId'.
      * @return This builder.
      */
    public com.finaccount.transactionservice.TransactionEvent.Builder setTransactionId(int value) {
      validate(fields()[0], value);
      this.transactionId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'transactionId' field has been set.
      * 거래 고유 ID
      * @return True if the 'transactionId' field has been set, false otherwise.
      */
    public boolean hasTransactionId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'transactionId' field.
      * 거래 고유 ID
      * @return This builder.
      */
    public com.finaccount.transactionservice.TransactionEvent.Builder clearTransactionId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'ownerName' field.
      * 거래 요청 사용자 이름
      * @return The value.
      */
    public java.lang.String getOwnerName() {
      return ownerName;
    }


    /**
      * Sets the value of the 'ownerName' field.
      * 거래 요청 사용자 이름
      * @param value The value of 'ownerName'.
      * @return This builder.
      */
    public com.finaccount.transactionservice.TransactionEvent.Builder setOwnerName(java.lang.String value) {
      validate(fields()[1], value);
      this.ownerName = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'ownerName' field has been set.
      * 거래 요청 사용자 이름
      * @return True if the 'ownerName' field has been set, false otherwise.
      */
    public boolean hasOwnerName() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'ownerName' field.
      * 거래 요청 사용자 이름
      * @return This builder.
      */
    public com.finaccount.transactionservice.TransactionEvent.Builder clearOwnerName() {
      ownerName = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'transactionType' field.
      * DEPOSIT | WITHDRAW | TRANSFER (요구사항 정리 문서 기준)
      * @return The value.
      */
    public java.lang.String getTransactionType() {
      return transactionType;
    }


    /**
      * Sets the value of the 'transactionType' field.
      * DEPOSIT | WITHDRAW | TRANSFER (요구사항 정리 문서 기준)
      * @param value The value of 'transactionType'.
      * @return This builder.
      */
    public com.finaccount.transactionservice.TransactionEvent.Builder setTransactionType(java.lang.String value) {
      validate(fields()[2], value);
      this.transactionType = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'transactionType' field has been set.
      * DEPOSIT | WITHDRAW | TRANSFER (요구사항 정리 문서 기준)
      * @return True if the 'transactionType' field has been set, false otherwise.
      */
    public boolean hasTransactionType() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'transactionType' field.
      * DEPOSIT | WITHDRAW | TRANSFER (요구사항 정리 문서 기준)
      * @return This builder.
      */
    public com.finaccount.transactionservice.TransactionEvent.Builder clearTransactionType() {
      transactionType = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'amount' field.
      * 거래 금액 (원 단위)
      * @return The value.
      */
    public long getAmount() {
      return amount;
    }


    /**
      * Sets the value of the 'amount' field.
      * 거래 금액 (원 단위)
      * @param value The value of 'amount'.
      * @return This builder.
      */
    public com.finaccount.transactionservice.TransactionEvent.Builder setAmount(long value) {
      validate(fields()[3], value);
      this.amount = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'amount' field has been set.
      * 거래 금액 (원 단위)
      * @return True if the 'amount' field has been set, false otherwise.
      */
    public boolean hasAmount() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'amount' field.
      * 거래 금액 (원 단위)
      * @return This builder.
      */
    public com.finaccount.transactionservice.TransactionEvent.Builder clearAmount() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'createdAt' field.
      * 거래 발생 시각 (ISO-8601)
      * @return The value.
      */
    public java.lang.String getCreatedAt() {
      return createdAt;
    }


    /**
      * Sets the value of the 'createdAt' field.
      * 거래 발생 시각 (ISO-8601)
      * @param value The value of 'createdAt'.
      * @return This builder.
      */
    public com.finaccount.transactionservice.TransactionEvent.Builder setCreatedAt(java.lang.String value) {
      validate(fields()[4], value);
      this.createdAt = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'createdAt' field has been set.
      * 거래 발생 시각 (ISO-8601)
      * @return True if the 'createdAt' field has been set, false otherwise.
      */
    public boolean hasCreatedAt() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'createdAt' field.
      * 거래 발생 시각 (ISO-8601)
      * @return This builder.
      */
    public com.finaccount.transactionservice.TransactionEvent.Builder clearCreatedAt() {
      createdAt = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'fromAccountId' field.
      * 출금/이체 출발 계좌 ID (DEPOSIT은 null). 요구사항 정리(2) API 응답의 fromAccountId 대응
      * @return The value.
      */
    public java.lang.Integer getFromAccountId() {
      return fromAccountId;
    }


    /**
      * Sets the value of the 'fromAccountId' field.
      * 출금/이체 출발 계좌 ID (DEPOSIT은 null). 요구사항 정리(2) API 응답의 fromAccountId 대응
      * @param value The value of 'fromAccountId'.
      * @return This builder.
      */
    public com.finaccount.transactionservice.TransactionEvent.Builder setFromAccountId(java.lang.Integer value) {
      validate(fields()[5], value);
      this.fromAccountId = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'fromAccountId' field has been set.
      * 출금/이체 출발 계좌 ID (DEPOSIT은 null). 요구사항 정리(2) API 응답의 fromAccountId 대응
      * @return True if the 'fromAccountId' field has been set, false otherwise.
      */
    public boolean hasFromAccountId() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'fromAccountId' field.
      * 출금/이체 출발 계좌 ID (DEPOSIT은 null). 요구사항 정리(2) API 응답의 fromAccountId 대응
      * @return This builder.
      */
    public com.finaccount.transactionservice.TransactionEvent.Builder clearFromAccountId() {
      fromAccountId = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'toAccountId' field.
      * 입금/이체 도착 계좌 ID (WITHDRAW는 null). 요구사항 정리(2) API 응답의 toAccountId 대응
      * @return The value.
      */
    public java.lang.Integer getToAccountId() {
      return toAccountId;
    }


    /**
      * Sets the value of the 'toAccountId' field.
      * 입금/이체 도착 계좌 ID (WITHDRAW는 null). 요구사항 정리(2) API 응답의 toAccountId 대응
      * @param value The value of 'toAccountId'.
      * @return This builder.
      */
    public com.finaccount.transactionservice.TransactionEvent.Builder setToAccountId(java.lang.Integer value) {
      validate(fields()[6], value);
      this.toAccountId = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'toAccountId' field has been set.
      * 입금/이체 도착 계좌 ID (WITHDRAW는 null). 요구사항 정리(2) API 응답의 toAccountId 대응
      * @return True if the 'toAccountId' field has been set, false otherwise.
      */
    public boolean hasToAccountId() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'toAccountId' field.
      * 입금/이체 도착 계좌 ID (WITHDRAW는 null). 요구사항 정리(2) API 응답의 toAccountId 대응
      * @return This builder.
      */
    public com.finaccount.transactionservice.TransactionEvent.Builder clearToAccountId() {
      toAccountId = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'status' field.
      * PENDING | SUCCESS | FAILED (Saga 보상 트랜잭션 대응, 요구사항 정리 문서 Transaction DB status)
      * @return The value.
      */
    public java.lang.String getStatus() {
      return status;
    }


    /**
      * Sets the value of the 'status' field.
      * PENDING | SUCCESS | FAILED (Saga 보상 트랜잭션 대응, 요구사항 정리 문서 Transaction DB status)
      * @param value The value of 'status'.
      * @return This builder.
      */
    public com.finaccount.transactionservice.TransactionEvent.Builder setStatus(java.lang.String value) {
      validate(fields()[7], value);
      this.status = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'status' field has been set.
      * PENDING | SUCCESS | FAILED (Saga 보상 트랜잭션 대응, 요구사항 정리 문서 Transaction DB status)
      * @return True if the 'status' field has been set, false otherwise.
      */
    public boolean hasStatus() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'status' field.
      * PENDING | SUCCESS | FAILED (Saga 보상 트랜잭션 대응, 요구사항 정리 문서 Transaction DB status)
      * @return This builder.
      */
    public com.finaccount.transactionservice.TransactionEvent.Builder clearStatus() {
      status = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public TransactionEvent build() {
      try {
        TransactionEvent record = new TransactionEvent();
        record.transactionId = fieldSetFlags()[0] ? this.transactionId : (java.lang.Integer) defaultValue(fields()[0]);
        record.ownerName = fieldSetFlags()[1] ? this.ownerName : (java.lang.String) defaultValue(fields()[1]);
        record.transactionType = fieldSetFlags()[2] ? this.transactionType : (java.lang.String) defaultValue(fields()[2]);
        record.amount = fieldSetFlags()[3] ? this.amount : (java.lang.Long) defaultValue(fields()[3]);
        record.createdAt = fieldSetFlags()[4] ? this.createdAt : (java.lang.String) defaultValue(fields()[4]);
        record.fromAccountId = fieldSetFlags()[5] ? this.fromAccountId : (java.lang.Integer) defaultValue(fields()[5]);
        record.toAccountId = fieldSetFlags()[6] ? this.toAccountId : (java.lang.Integer) defaultValue(fields()[6]);
        record.status = fieldSetFlags()[7] ? this.status : (java.lang.String) defaultValue(fields()[7]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<TransactionEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<TransactionEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<TransactionEvent>
    READER$ = (org.apache.avro.io.DatumReader<TransactionEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeInt(this.transactionId);

    out.writeString(this.ownerName);

    out.writeString(this.transactionType);

    out.writeLong(this.amount);

    out.writeString(this.createdAt);

    if (this.fromAccountId == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeInt(this.fromAccountId);
    }

    if (this.toAccountId == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeInt(this.toAccountId);
    }

    out.writeString(this.status);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.transactionId = in.readInt();

      this.ownerName = in.readString();

      this.transactionType = in.readString();

      this.amount = in.readLong();

      this.createdAt = in.readString();

      if (in.readIndex() != 1) {
        in.readNull();
        this.fromAccountId = null;
      } else {
        this.fromAccountId = in.readInt();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.toAccountId = null;
      } else {
        this.toAccountId = in.readInt();
      }

      this.status = in.readString();

    } else {
      for (int i = 0; i < 8; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.transactionId = in.readInt();
          break;

        case 1:
          this.ownerName = in.readString();
          break;

        case 2:
          this.transactionType = in.readString();
          break;

        case 3:
          this.amount = in.readLong();
          break;

        case 4:
          this.createdAt = in.readString();
          break;

        case 5:
          if (in.readIndex() != 1) {
            in.readNull();
            this.fromAccountId = null;
          } else {
            this.fromAccountId = in.readInt();
          }
          break;

        case 6:
          if (in.readIndex() != 1) {
            in.readNull();
            this.toAccountId = null;
          } else {
            this.toAccountId = in.readInt();
          }
          break;

        case 7:
          this.status = in.readString();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










